"use client";
import { useState } from "react";
import { apiPost } from "@/lib/api-client";
import type { ProductMaterial } from "@/lib/types";
import { Button, Dialog, Field, Input, Select, Textarea } from "@/components/ui";

export function ProductMaterialEditor({productId,open,onClose,onSaved}:{productId:string;open:boolean;onClose:()=>void;onSaved:(item:ProductMaterial)=>void}){
  const [title,setTitle]=useState("");const [type,setType]=useState("DETAIL_AID");const [messageSummary,setMessageSummary]=useState("");const [externalUrl,setExternalUrl]=useState("https://example.test/material.pdf");const [version,setVersion]=useState("");const [approvalCode,setApprovalCode]=useState("");const [effectiveDate,setEffectiveDate]=useState("2026-07-01");const [expiryDate,setExpiryDate]=useState("2027-01-01");const [busy,setBusy]=useState(false);
  async function save(){setBusy(true);try{const item=await apiPost<ProductMaterial>("/api/product-materials",{productId,title,type,messageSummary,externalUrl,version,approvalCode,effectiveDate,expiryDate});onSaved(item);onClose();}finally{setBusy(false);}}
  return <Dialog open={open} onClose={onClose} title="创建产品资料版本"><div className="space-y-3"><Field label="标题" required><Input value={title} onChange={e=>setTitle(e.target.value)}/></Field><Field label="资料类型"><Select className="w-full" value={type} onChange={e=>setType(e.target.value)}><option value="DETAIL_AID">沟通卡</option><option value="SLIDE_DECK">幻灯</option><option value="PATIENT_EDUCATION">患者教育</option><option value="CLINICAL_REPRINT">文献</option></Select></Field><Field label="合规话术摘要" required><Textarea value={messageSummary} onChange={e=>setMessageSummary(e.target.value)}/></Field><Field label="外部链接" required><Input value={externalUrl} onChange={e=>setExternalUrl(e.target.value)}/></Field><div className="grid grid-cols-2 gap-3"><Field label="版本" required><Input value={version} onChange={e=>setVersion(e.target.value)}/></Field><Field label="批准编号"><Input value={approvalCode} onChange={e=>setApprovalCode(e.target.value)}/></Field><Field label="生效日期"><Input type="date" value={effectiveDate} onChange={e=>setEffectiveDate(e.target.value)}/></Field><Field label="失效日期"><Input type="date" value={expiryDate} onChange={e=>setExpiryDate(e.target.value)}/></Field></div><div className="flex justify-end gap-2"><Button variant="ghost" onClick={onClose}>取消</Button><Button disabled={busy||!title||!version||!messageSummary} onClick={save}>保存草稿</Button></div></div></Dialog>
}
